"""created login route

Revision ID: 9ff023b1a38f
Revises: 5a209430ab25
Create Date: 2026-03-17 12:38:02.379088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff023b1a38f'
down_revision: Union[str, Sequence[str], None] = '5a209430ab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logs',
    sa.Column('messages', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Logs_id'), 'Logs', ['id'], unique=False)
    op.alter_column('auth_accounts', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GOOGLE', 'APPLE', 'EMAIL', name='authprovider'),
               existing_nullable=False)
    op.create_index('uix_provider_user', 'auth_accounts', ['provider', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_provider_user', table_name='auth_accounts')
    op.alter_column('auth_accounts', 'provider',
               existing_type=sa.Enum('GOOGLE', 'APPLE', 'EMAIL', name='authprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_Logs_id'), table_name='Logs')
    op.drop_table('Logs')
    # ### end Alembic commands ###